### ISSUE TITLE
Reconsider Math.floor for token expiry time

### ISSUE THREAD

**Issue by gigili** [gigili/good-food-tracker-api#36]
When generating a new access token Math.floor is used to round and update expiry time longer by 2 hours. 

This should be reconsider and created in a way were we do not need to relay on the Math functions so that the validity of token can be verified better

**Comment by subhamX** [comment]
Hi @gigili. I would like to work on this issue. If I am getting it correctly, you want to change the current logic of handing of time at [L43](https://github.com/gigili/good-food-tracker-api/blob/152813a9408d9cdeedca4a7699b4047c8cef1811/helpers/utilities.ts#L43) and [L47](https://github.com/gigili/good-food-tracker-api/blob/152813a9408d9cdeedca4a7699b4047c8cef1811/helpers/utilities.ts#L47) to something which isn't dependent of `Math.round`.

**Comment by gigili** [comment]
Yes, what I was thinking of is finding a way to set a timestamp that is +2 hours from the moment of execution, but not be rounded or floored in this case. If you have any suggestions, all contributions are welcomed.

**Comment by subhamX** [comment]
Hi. JS Date object does have methods which allow us to add time (2 hours in our case) directly. The above PR implements the same. Do let me know what you feel about it.
